OLS(Ordinary Least Square)

In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics

In [20]:



data = {'Houres of sun': [2, 3, 5, 7,9],
        'Ice Creame': [4, 5, 7, 10,15]}



In [21]:
dataset = pd.DataFrame(data)

In [22]:
dataset

Houres of sun  Ice Creame
0              2           4
1              3           5
2              5           7
3              7          10
4              9          15

In [23]:
x=dataset["Houres of sun"]
y=dataset['Ice Creame']

In [24]:
y

0     4
1     5
2     7
3    10
4    15
Name: Ice Creame, dtype: int64

In [25]:
linear_regressor = LinearRegression()

In [26]:
X_train = x.values.reshape((-1, 1))
y_train = y.values.reshape((-1, 1))

In [27]:
X_train

array([[2],
       [3],
       [5],
       [7],
       [9]])

In [28]:
linear_regressor.fit(X_train, y_train)

LinearRegression()

In [29]:
linear_regressor.coef_ #slope A

array([[1.51829268]])

In [30]:
linear_regressor.intercept_ # intercept B

array([0.30487805])

GD(Gradient Descent)

In [31]:
from sklearn.linear_model import SGDRegressor

In [32]:
GD_model = SGDRegressor(max_iter=50, eta0=0.001)
GD_model

SGDRegressor(eta0=0.001, max_iter=50)

In [33]:
GD_model.fit(X_train, y_train.squeeze())

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_stochastic_gradient.py:1548: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(


SGDRegressor(eta0=0.001, max_iter=50)

In [34]:
 y_hat = GD_model.predict(X_train)
 y_hat


array([ 3.11313423,  4.5556454 ,  7.44066775, 10.32569009, 13.21071244])

In [35]:
GD_model.intercept_, GD_model.coef_

(array([0.22811189]), array([1.44251117]))