In [8]:
import numpy as np

In [2]:
array =  np.arange(10) 

In [3]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones([2,3,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [7]:
np.random.randint(0,100,10) #4

array([81, 68, 32, 58, 72, 14, 92, 13, 11, 51])

In [15]:
np.random.uniform(0,1,10) #5

array([0.06768087, 0.58834626, 0.30294871, 0.26013781, 0.36196409,
       0.75771687, 0.99730998, 0.0256644 , 0.2285155 , 0.66678991])

In [16]:
np.linspace(0,1,num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [23]:
np.arange(0,1.1,0.25)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [24]:
np.arange(-1,1.1,0.25)

array([-1.  , -0.75, -0.5 , -0.25,  0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [28]:
np.sin(np.arange(0,361,90)*np.pi/180)

array([ 0.0000000e+00,  1.0000000e+00,  1.2246468e-16, -1.0000000e+00,
       -2.4492936e-16])

In [32]:
np.sin(np.arange(0,361,90))

array([ 0.        ,  0.89399666, -0.80115264, -0.17604595,  0.95891572])

In [33]:
np.arange(0,361,90)

array([  0,  90, 180, 270, 360])

In [34]:
#E2:1
arr1=np.array([[1,2],[8,9]])

In [35]:
arr1

array([[1, 2],
       [8, 9]])

In [36]:
arr1*2

array([[ 2,  4],
       [16, 18]])

In [42]:
#E2:2
arr2=np.array([[1,2,3],[8,9,10],[2,9,10]])

In [43]:
arr2

array([[ 1,  2,  3],
       [ 8,  9, 10],
       [ 2,  9, 10]])

In [39]:
arr2+5

array([[ 6,  7,  8],
       [13, 14, 15]])

In [44]:
#E2:3
arr3=np.array([[1,2,3,4],[7,8,9,10],[2,8,2,10],[7,8,9,6]])



In [45]:
arr3

array([[ 1,  2,  3,  4],
       [ 7,  8,  9, 10],
       [ 2,  8,  2, 10],
       [ 7,  8,  9,  6]])

In [46]:
arr3-10

array([[-9, -8, -7, -6],
       [-3, -2, -1,  0],
       [-8, -2, -8,  0],
       [-3, -2, -1, -4]])

In [47]:
#E2:4
arr4=np.array([[1,2,3,4,2],[7,8,9,10,2],[2,8,2,10,2],[7,8,9,6,2],[1,2,3,2,2]])

In [48]:
arr4

array([[ 1,  2,  3,  4,  2],
       [ 7,  8,  9, 10,  2],
       [ 2,  8,  2, 10,  2],
       [ 7,  8,  9,  6,  2],
       [ 1,  2,  3,  2,  2]])

In [49]:
arr4/2

array([[0.5, 1. , 1.5, 2. , 1. ],
       [3.5, 4. , 4.5, 5. , 1. ],
       [1. , 4. , 1. , 5. , 1. ],
       [3.5, 4. , 4.5, 3. , 1. ],
       [0.5, 1. , 1.5, 1. , 1. ]])

In [50]:
#E2:5
arr5=np.array([[1,2,3,4,2,3],[7,8,9,10,2,3],[2,8,2,10,2,5],[7,8,9,6,2,2],[1,2,3,2,2,2],[1,2,2,3,4,5]])

In [51]:
arr5

array([[ 1,  2,  3,  4,  2,  3],
       [ 7,  8,  9, 10,  2,  3],
       [ 2,  8,  2, 10,  2,  5],
       [ 7,  8,  9,  6,  2,  2],
       [ 1,  2,  3,  2,  2,  2],
       [ 1,  2,  2,  3,  4,  5]])

In [52]:
import math

In [55]:
np.sqrt(arr5)

array([[1.        , 1.41421356, 1.73205081, 2.        , 1.41421356,
        1.73205081],
       [2.64575131, 2.82842712, 3.        , 3.16227766, 1.41421356,
        1.73205081],
       [1.41421356, 2.82842712, 1.41421356, 3.16227766, 1.41421356,
        2.23606798],
       [2.64575131, 2.82842712, 3.        , 2.44948974, 1.41421356,
        1.41421356],
       [1.        , 1.41421356, 1.73205081, 1.41421356, 1.41421356,
        1.41421356],
       [1.        , 1.41421356, 1.41421356, 1.73205081, 2.        ,
        2.23606798]])

In [56]:
#E2:6
arr6=np.array([[1,2],[8,9]])

In [57]:
arr6

array([[1, 2],
       [8, 9]])

In [59]:
np.matmul(arr6,arr6)

array([[17, 20],
       [80, 97]])

In [62]:
np.dot(arr6,arr6)

array([[17, 20],
       [80, 97]])

In [60]:
#E2:7
arr3=np.array([[1,2,3],[8,9,10],[2,9,10]])

In [61]:
np.dot(arr3,arr3)

array([[ 23,  47,  53],
       [100, 187, 214],
       [ 94, 175, 196]])

In [64]:
#E2:8
arr81=np.array([[1,2,2],[1,2,3]])
arr82=np.array([[1,2],[1,2],[2,1]])



In [65]:
arr81

array([[1, 2, 2],
       [1, 2, 3]])

In [66]:
arr82

array([[1, 2],
       [1, 2],
       [2, 1]])

In [67]:
np.matmul(arr81,arr82)

array([[7, 8],
       [9, 9]])

In [ ]:
#E2:10

In [ ]:
#Numpy(ArrayIndexing)

In [68]:
#Q1
ar1=np.arange(0,10)

In [69]:
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
ar1[3]

3

In [74]:
#Q2
ar2=np.random.randint(5,size=(3,3))

In [75]:
ar2.shape

(3, 3)

In [76]:
ar2

array([[3, 2, 4],
       [0, 2, 4],
       [1, 0, 1]])

In [78]:
ar2[2,1]

0

In [95]:
#Q3
ar3=np.random.randint(5,size=(4,4))

In [96]:
ar3

array([[2, 2, 1, 2],
       [2, 2, 1, 0],
       [1, 4, 3, 3],
       [2, 3, 0, 1]])

In [98]:
ar3[:2,2:]

array([[1, 2],
       [1, 0]])

In [104]:
#Q4
ar4=np.arange(0,10)

In [105]:
ar4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
arr_copy = ar4[0:3].copy()


In [111]:
arr_copy

array([0, 1, 2])

In [112]:
#Q5
ar5=np.random.randint(5,size=(3,3))


In [113]:
ar5


array([[0, 3, 4],
       [0, 3, 3],
       [4, 0, 4]])

In [115]:
arr_copy1 = ar5[0:2,0:2].copy()

In [116]:
arr_copy1

array([[0, 3],
       [0, 3]])

In [119]:
#q6
ar6=np.arange(0,9).reshape(3,3)

In [120]:
ar6

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
#q7

ar7=np.random.randint(5,size=(4,4))

In [11]:
ar7.reshape(-1)

array([4, 2, 3, 3, 4, 2, 3, 3, 4, 1, 3, 3, 4, 1, 4, 3])

In [12]:
#q8
ar81=np.arange(0,4)
ar82=np.arange(0,4)



In [13]:
ar81

array([0, 1, 2, 3])

In [14]:
concatenated_array = np.concatenate((ar81, ar82))

In [15]:
concatenated_array

array([0, 1, 2, 3, 0, 1, 2, 3])

In [21]:
#q9
ar91 = np.array([[1, 2], [3, 4]])

ar92 = np.array([[5, 6, 7], [8, 9, 10]])

# Concatenate the two arrays horizontally
np.hstack((ar91, ar92))



array([[ 1,  2,  5,  6,  7],
       [ 3,  4,  8,  9, 10]])

In [23]:
#q10
ar91 = np.array([[1, 2], [3, 4]])


ar92 = np.array([[5, 6], [7, 8], [9, 10]])

# Concatenate the two arrays vertical
np.vstack((ar91, ar92))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [92]:
#q11

ar11=np.random.rand(4,4)

In [93]:
ar11


array([[0.79217406, 0.32596704, 0.42787363, 0.23679492],
       [0.41658211, 0.3236347 , 0.7948466 , 0.35867672],
       [0.80937018, 0.51924521, 0.08335722, 0.44362801],
       [0.11412939, 0.08603253, 0.94643019, 0.21620799]])

In [26]:
half1, half2 = np.split(ar11, 2)

In [27]:
half1

array([[0.39501974, 0.80445885, 0.70881326, 0.45157897],
       [0.0625333 , 0.95528033, 0.66072001, 0.03960043]])

In [28]:
half2

array([[0.17103706, 0.48678533, 0.83069169, 0.07142338],
       [0.70927676, 0.2904684 , 0.42384117, 0.61744933]])

In [29]:
#q12 vertical
halfv1, halfv2 = np.split(ar11, 2,axis=1)



In [30]:
halfv1

array([[0.39501974, 0.80445885],
       [0.0625333 , 0.95528033],
       [0.17103706, 0.48678533],
       [0.70927676, 0.2904684 ]])

In [94]:
#Q13
# Split the array into four equal subarrays
subarrays = np.split(ar11, 2, axis=0)
subarray1, subarray2 = np.split(subarrays[0], 2, axis=1)
subarray3, subarray4 = np.split(subarrays[1], 2, axis=1)

In [32]:
subarray1

array([[0.39501974, 0.80445885],
       [0.0625333 , 0.95528033]])

In [33]:
#q14
ar14 = np.arange(10)

# Set all odd elements to zero
ar14[ar14 % 2 != 0] = 0

In [34]:
ar14

array([0, 0, 2, 0, 4, 0, 6, 0, 8, 0])

In [2]:
#Q15

ar15=np.random.rand(3,3)

In [3]:
ar15

array([[0.84527194, 0.34983884, 0.5340606 ],
       [0.68392847, 0.02781576, 0.92275356],
       [0.07700893, 0.05540738, 0.25005464]])

In [6]:
ar15[:1]=0
ar15

array([[0.        , 0.        , 0.        ],
       [0.68392847, 0.02781576, 0.92275356],
       [0.07700893, 0.05540738, 0.25005464]])

In [7]:
ar15[1:]

array([[0.68392847, 0.02781576, 0.92275356],
       [0.07700893, 0.05540738, 0.25005464]])

In [8]:
#16

arr16=np.random.rand(3,3)
arr16

array([[0.59621484, 0.44171695, 0.21714009],
       [0.92870436, 0.78455673, 0.52659857],
       [0.18723751, 0.05859758, 0.23746496]])

In [16]:
arr16[:,2:]=0

In [17]:
arr16

array([[0.59621484, 0.44171695, 0.        ],
       [0.92870436, 0.78455673, 0.        ],
       [0.18723751, 0.05859758, 0.        ]])

In [77]:
#q17


arr172=np.random.rand(3,3)
arr172

array([[0.11380612, 0.64592148, 0.39106866],
       [0.3676558 , 0.09611893, 0.38974361],
       [0.64920961, 0.73185941, 0.07843484]])

In [79]:
arr172[:2,1:]=0


In [80]:
arr172

array([[0.11380612, 0.        , 0.        ],
       [0.3676558 , 0.        , 0.        ],
       [0.64920961, 0.73185941, 0.07843484]])

In [82]:
#Q18
arr18=np.arange(0,10)
arr18

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
arr18_copy = arr18.copy()
arr18_copy*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [85]:
#q19
arr19=np.random.rand(3,3)
arr19

array([[0.10650666, 0.26612585, 0.25729947],
       [0.34629804, 0.08698842, 0.08613953],
       [0.17545258, 0.07303311, 0.70256296]])

In [86]:
arr19_copy = arr19.copy()
arr19_copy+1

array([[1.10650666, 1.26612585, 1.25729947],
       [1.34629804, 1.08698842, 1.08613953],
       [1.17545258, 1.07303311, 1.70256296]])

In [87]:
#q20
arr20=np.random.rand(3,3)
arr20

array([[0.35628477, 0.21846055, 0.24582595],
       [0.29318343, 0.00766624, 0.89535716],
       [0.56260291, 0.67479614, 0.57929917]])

In [88]:
arr20_copy = arr20[0:2,0:2].copy()

In [95]:
arr20_copy

array([[0.35628477, 0.21846055],
       [0.29318343, 0.00766624]])

In [35]:
arr_2d=np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [37]:
arr_2d[:,1:]


array([[10, 15],
       [25, 30],
       [40, 45]])

In [123]:
a1 = np.random.randn(5,5)


In [124]:
a1

array([[-0.9253603 ,  0.4456577 , -1.53527286, -1.14728287, -0.94863826],
       [ 0.15404507,  0.25735708,  0.21267714,  2.38142493,  1.46965988],
       [ 0.04278394,  1.35903669,  1.44238646, -0.68801381,  0.53768918],
       [-0.07292164, -0.7439479 , -0.32154091, -0.86823044, -1.12563636],
       [ 1.15956296,  0.78486793,  1.12373998, -1.3991615 , -1.08966686]])

In [126]:
a1.mean+a1.std*np.random.randn(5,5)

TypeError: unsupported operand type(s) for *: 'builtin_function_or_method' and 'float'

In [129]:
x=a1.mean+a1.std*np.random.randn(5,5)

TypeError: unsupported operand type(s) for *: 'builtin_function_or_method' and 'float'

In [130]:
mean=75

In [131]:
sd=4

In [134]:
a2=4*np.random.randn(5,5)+75

In [135]:
a2

array([[71.94973702, 74.03484149, 72.55937916, 76.51287813, 79.11714214],
       [71.05724007, 76.60608004, 75.50346977, 70.62192027, 78.61303042],
       [72.49173169, 73.12672075, 81.89954566, 71.77558685, 73.38400026],
       [73.45613554, 79.84403767, 78.19848158, 78.76971319, 75.30393051],
       [74.95118557, 75.11860117, 73.78184344, 80.69982147, 71.89541443]])

In [136]:
A=np.array([-2,5,4,-8,0])
print(A)

[-2  5  4 -8  0]


In [137]:
print(np.sort(A)) #Ascending
print(- np.sort(A)) #Descending

[-8 -2  0  4  5]
[ 8  2  0 -4 -5]


In [143]:
np.sort(A)[::-1]

array([ 5,  4,  0, -2, -8])

In [145]:
A.sort(reverse=True)

TypeError: sort() got an unexpected keyword argument 'reverse'

In [148]:
countries = np.array(['France', 'Germany', 'USA','Russia','USA','Mexico','Germany'])
np.unique(countries)

array(['France', 'Germany', 'Mexico', 'Russia', 'USA'], dtype='<U7')

In [153]:
np.in1d(['France','USA','Sweden'],countries)


array([ True,  True, False])