# Numpy (Universal Array Function)

In [1]:
import numpy as np

In [2]:
#Q1
arr = np.random.rand(3, 3)

# Compute the exponential of each element using np.exp()
exp_arr = np.exp(arr)

In [3]:
exp_arr

array([[1.99771427, 1.56179348, 2.07169269],
       [1.0501943 , 1.03979939, 2.28683511],
       [2.62737358, 1.68433048, 1.77537052]])

In [4]:
arr

array([[0.69200366, 0.44583483, 0.728366  ],
       [0.0489752 , 0.0390278 , 0.82716882],
       [0.96598471, 0.52136815, 0.57400914]])

In [5]:
#q2

arr2 = np.random.rand(4, 4)

#using np.sin()
sin_arr = np.sin(arr2)

In [6]:
sin_arr

array([[0.38650962, 0.8305102 , 0.47196019, 0.79291978],
       [0.57610067, 0.83248194, 0.77430532, 0.65956378],
       [0.40506985, 0.17734875, 0.0466003 , 0.26671425],
       [0.77638328, 0.58471627, 0.0752342 , 0.03012065]])

In [7]:
#q3

arr3 = np.random.rand(5, 5)

#using np.log()
log_arr = np.log(arr3)

In [8]:
log_arr

array([[-0.31516633, -0.04627539, -1.57480079, -0.06963614, -6.02220252],
       [-2.1069958 , -0.49215909, -1.08008315, -1.41828649, -0.05426448],
       [-2.08510113, -0.87202205, -2.98612214, -3.54296722, -4.01317331],
       [-0.4843183 , -0.50110543, -0.73486767, -0.41555816, -0.12774831],
       [-1.09422354, -1.76212363, -1.61195389, -1.28130817, -0.17900209]])

In [9]:
#Q4

arr4 = np.random.rand(2, 2)
#using np.sqrt()
sqrt_arr = np.sqrt(arr4)

In [10]:
sqrt_arr

array([[0.99794379, 0.94094022],
       [0.6143006 , 0.67618626]])

In [11]:
#Q5
arr5 = np.random.rand(6, 6)
#np.floor()
floor_arr = np.floor(arr5)


In [12]:
floor_arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
arr5

array([[0.7476576 , 0.07748151, 0.62669607, 0.75627877, 0.69331185,
        0.34440616],
       [0.58397526, 0.57016974, 0.56793688, 0.72646732, 0.3304449 ,
        0.13322167],
       [0.33845107, 0.96229845, 0.38161038, 0.60255224, 0.05899458,
        0.99072183],
       [0.48947509, 0.4590879 , 0.27119662, 0.51268753, 0.11392017,
        0.26359396],
       [0.80446106, 0.82896515, 0.35972449, 0.96012216, 0.39144668,
        0.08261095],
       [0.17538645, 0.67136557, 0.4045878 , 0.80816944, 0.5725707 ,
        0.44410456]])

In [14]:
#Q7
arr7 = np.random.rand(4, 4)

#power of 2 using np.power()
power_arr = np.power(arr7, 2)

In [15]:
power_arr

array([[1.58281098e-01, 2.55514525e-01, 6.44876418e-01, 7.73703064e-04],
       [1.34074960e-01, 5.43561126e-01, 3.60582603e-02, 5.36584290e-01],
       [5.78404310e-01, 2.62637928e-01, 3.44630352e-01, 8.42989031e-02],
       [1.61116366e-02, 8.17985143e-01, 1.02153175e-02, 1.46952874e-01]])

In [16]:
#Q8
arr8 = np.random.randint(1, 11, size=5)

# Find the largest element using np.max()
largest_element = np.max(arr8)

In [17]:
arr8

array([ 8,  2,  1, 10,  6])

In [18]:
largest_element

10

In [19]:
#Q9
arr9 = np.random.random(size=10)

# Round each element to the nearest integer using np.round()
rounded_arr = np.round(arr9)

In [20]:
arr9

array([0.75991067, 0.10867442, 0.49420649, 0.72073258, 0.34357842,
       0.93466686, 0.78722228, 0.22020347, 0.35945991, 0.11388637])

In [21]:
rounded_arr

array([1., 0., 0., 1., 0., 1., 1., 0., 0., 0.])

In [22]:
#Q10
arr10 = np.random.randint(1, 101, size=7)

# Find the index of the largest element using np.argmax()
index_of_largest = np.argmax(arr10)

In [23]:
arr10

array([98, 63, 78, 58, 73, 44, 44])

In [24]:
index_of_largest

0

In [25]:
#Q11
arr1_11 = np.random.randint(1, 11, size=(3, 3))
arr2_11 = np.random.randint(1, 11, size=(3, 3))

# Add the two arrays together element-wise using np.add()
arr_11 = np.add(arr1_11, arr2_11)


In [26]:
arr_11

array([[10, 12, 16],
       [11,  5, 18],
       [15,  3,  8]])

In [27]:
#Q12
arr12 = np.random.randint(0, 101, size=12)

# Limit the values in the array to a range between 10 and 90 using np.clip()
clipped_arr = np.clip(arr12, 10, 90)

In [28]:
arr12

array([30, 37, 86, 43, 31, 58, 55, 74, 27, 67, 33, 37])

In [29]:
clipped_arr

array([30, 37, 86, 43, 31, 58, 55, 74, 27, 67, 33, 37])

# Numpy (Array Processing)


In [31]:
#Q1:Create a NumPy array with 10 random integers between 0 and 100.
array1 = np.random.randint(0, 100, 10)

In [32]:
array1

array([93, 12, 21, 38, 68, 51, 65, 14, 52, 25])

In [33]:
#Q2:Use the np.where() function to create a new array with the same shape as the previous one,
# where values less than 50 are replaced with -1 and values greater than or equal to 50 are replaced with 1.
new_array = np.where(original_array < 50, -1, 1)

In [34]:
new_array

array([ 1,  1,  1,  1, -1, -1,  1,  1, -1, -1])

In [39]:
#Q3:Calculate the mean, median, and standard deviation of the original array.
mean = np.mean(array1)
median = np.median(array1)
std_dev = np.std(array1)
print("\nMean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)


Mean: 43.9
Median: 44.5
Standard Deviation: 25.260443384865592


In [35]:
#q4:Create a boolean array that is True where the values in the original array are even, and False otherwise.
even_array = array1 % 2 == 0

In [36]:
even_array

array([False,  True, False,  True,  True, False, False,  True,  True,
       False])

In [37]:
#Q5:Sort the original array in ascending order.
np.sort(array1)

array([12, 14, 21, 25, 38, 51, 52, 65, 68, 93])

In [38]:
#Q6: Find the unique values in the original array.
np.unique(array1)

array([12, 14, 21, 25, 38, 51, 52, 65, 68, 93])

In [41]:
#Q7: Use the np.in1d() function to create a boolean array indicating which elements of the originalarray are also present in a new array with 5 random integers between 0 and 100.
random_array = np.random.randint(0, 100, 5)
in1d_array = np.in1d(array1, random_array)
in1d_array 

array([False,  True, False, False, False, False, False, False, False,
       False])

In [42]:
#Q8: Save the original array to a text file named "my_array.txt" using the np.savetxt() function.
np.savetxt("my_array.txt", array1)
